#!/usr/bin/env python3

import argparse
import csv
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple


DECISIONS = {
    "switch_genre_fast",
    "increase_energy",
    "maintain_vibe",
    "go_all_out",
}


def clamp_int(n: int, min_v: int, max_v: int) -> int:
    return max(min_v, min(max_v, n))


def bin_to_step(value: int, step: int, min_bin: int, max_bin: int) -> int:
    step = max(1, int(step))
    b = (int(value) // step) * step
    return clamp_int(b, min_bin, max_bin)


def parse_int(raw: object, default: int = 0) -> int:
    try:
        if raw is None:
            return default
        s = str(raw).strip()
        if not s:
            return default
        return int(float(s))
    except Exception:
        return default


def normalize_style(raw: object) -> str:
    s = ("" if raw is None else str(raw)).strip().lower()
    return s or "default"


def normalize_pressure_state(raw: object) -> str:
    s = ("" if raw is None else str(raw)).strip().lower()
    return s or "unknown"


def normalize_decision(raw: object) -> Optional[str]:
    s = ("" if raw is None else str(raw)).strip()
    if s in DECISIONS:
        return s
    return None


def outcome_weight(raw: object) -> float:
    s = ("" if raw is None else str(raw)).strip().lower()
    if s in ("win", "won", "winner"):
        return 1.0
    if s in ("draw", "tie"):
        return 0.7
    if s in ("lose", "lost", "loser"):
        return 0.25
    if not s or s == "unknown":
        return 1.0
    return 0.8


@dataclass(frozen=True)
class PolicyKey:
    style: str
    pressure_state: str
    bpm_bin: int
    likes_bin: int
    coins_bin: int
    viewers_bin: int


def iter_rows(path: str) -> Iterable[dict]:
    with open(path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            yield row


def build_policy(in_path: str) -> Tuple[Dict[PolicyKey, str], Dict[PolicyKey, float]]:
    # scores[key][decision] = accumulated weight
    scores: Dict[PolicyKey, Dict[str, float]] = defaultdict(lambda: defaultdict(float))

    for row in iter_rows(in_path):
        style = normalize_style(row.get("style"))
        pressure_state = normalize_pressure_state(row.get("pressure_state"))

        bpm = parse_int(row.get("current_song_bpm"))
        likes = parse_int(row.get("likes_per_min"))
        coins = parse_int(row.get("coins_per_min"))
        viewers = parse_int(row.get("viewers_change"))

        decision = normalize_decision(row.get("decision"))
        if decision is None:
            continue

        w = outcome_weight(row.get("outcome"))

        key = PolicyKey(
            style=style,
            pressure_state=pressure_state,
            bpm_bin=bin_to_step(bpm, 5, 60, 220),
            likes_bin=bin_to_step(likes, 10, 0, 1000),
            coins_bin=bin_to_step(coins, 2, 0, 500),
            viewers_bin=bin_to_step(viewers, 5, -500, 500),
        )

        scores[key][decision] += w

    best_decision: Dict[PolicyKey, str] = {}
    confidence: Dict[PolicyKey, float] = {}

    for key, dec_scores in scores.items():
        total = sum(dec_scores.values())
        if total <= 0:
            continue
        best = max(dec_scores.items(), key=lambda kv: kv[1])
        best_decision[key] = best[0]
        confidence[key] = float(best[1] / total)

    return best_decision, confidence


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def write_upserts(out_path: str, decisions: Dict[PolicyKey, str], conf: Dict[PolicyKey, float]) -> None:
    lines: List[str] = []
    lines.append("-- Generated by tool/dj_ai_ml/build_policy_from_events.py")
    lines.append("-- Upserts into public.dj_ai_policy")
    lines.append("")

    # Deterministic ordering for review.
    keys = sorted(
        decisions.keys(),
        key=lambda k: (k.style, k.pressure_state, k.bpm_bin, k.likes_bin, k.coins_bin, k.viewers_bin),
    )

    for k in keys:
        d = decisions[k]
        c = conf.get(k, 0.0)
        lines.append(
            "insert into public.dj_ai_policy "
            "(style, pressure_state, bpm_bin, likes_bin, coins_bin, viewers_bin, decision, confidence, updated_at) values "
            f"('{sql_escape(k.style)}','{sql_escape(k.pressure_state)}',{k.bpm_bin},{k.likes_bin},{k.coins_bin},{k.viewers_bin}," \
            f"'{sql_escape(d)}',{c:.6f},now()) "
            "on conflict (style, pressure_state, bpm_bin, likes_bin, coins_bin, viewers_bin) do update set "
            "decision=excluded.decision, confidence=excluded.confidence, updated_at=excluded.updated_at;"
        )

    lines.append("")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="in_path", required=True, help="Input CSV exported from dj_ai_events")
    ap.add_argument("--out", dest="out_path", required=True, help="Output SQL upsert file")
    args = ap.parse_args()

    decisions, conf = build_policy(args.in_path)
    write_upserts(args.out_path, decisions, conf)
    print(f"Wrote {len(decisions)} policy rows to {args.out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
