-- Ensure the canonical subscriptions catalog rows exist in public.subscriptions.
-- Some admin/legacy clients look up plans via public.subscriptions (e.g. by plan_code).

create extension if not exists pgcrypto;

-- Create the table if it doesn't exist (legacy-safe).
create table if not exists public.subscriptions (
	id integer generated by default as identity primary key,
	name text not null,
	price integer not null default 0,
	duration_days integer not null default 30,
	features jsonb not null default '{}'::jsonb,
	status text not null default 'active',
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- Ensure expected columns exist even on legacy tables.
alter table public.subscriptions
	add column if not exists name text,
	add column if not exists price integer,
	add column if not exists duration_days integer,
	add column if not exists features jsonb,
	add column if not exists status text,
	add column if not exists created_at timestamptz,
	add column if not exists updated_at timestamptz,
	add column if not exists plan_code text,
	add column if not exists plan_name text;

-- Best-effort uniqueness on name (needed by some upserts, but don't fail if legacy duplicates exist).
do $$
begin
	begin
		create unique index if not exists subscriptions_name_unique on public.subscriptions (name);
	exception
		when unique_violation then
			raise notice 'Could not create subscriptions_name_unique due to duplicate names. Seed will use WHERE NOT EXISTS.';
		when duplicate_table then null;
		when duplicate_object then null;
	end;
end $$;

-- Seed canonical rows if missing.
do $$
declare
	user_id_required boolean := false;
	user_id_type text := null;
	user_id_has_default boolean := false;
	seed_user_id_expr text := null;
	has_plan_code boolean := false;
	has_plan_name boolean := false;
	has_name boolean := false;
	missing_required_cols text[] := array[]::text[];
	col record;
	insert_cols text;
	insert_vals text;
	where_pred text;
	plan_code_value text;
	plan_name_value text;
	plan_price_value integer;
	plan_duration_days_value integer;
	plan_features_expr text;
	expr text;
begin
	-- Column existence probes used for predicates/backfills.
	select exists (
		select 1 from information_schema.columns
		where table_schema = 'public' and table_name = 'subscriptions' and column_name = 'plan_code'
	) into has_plan_code;
	select exists (
		select 1 from information_schema.columns
		where table_schema = 'public' and table_name = 'subscriptions' and column_name = 'plan_name'
	) into has_plan_name;
	select exists (
		select 1 from information_schema.columns
		where table_schema = 'public' and table_name = 'subscriptions' and column_name = 'name'
	) into has_name;

	-- Detect legacy user_id column requirements (some deployments incorrectly modeled this table).
	select
		(c.is_nullable = 'NO') as required,
		c.data_type,
		(c.column_default is not null) as has_default
	into user_id_required, user_id_type, user_id_has_default
	from information_schema.columns c
	where c.table_schema = 'public'
		and c.table_name = 'subscriptions'
		and c.column_name = 'user_id'
	limit 1;

	if user_id_required and not coalesce(user_id_has_default, false) then
		if user_id_type = 'uuid' then
			seed_user_id_expr := 'gen_random_uuid()';
		elsif user_id_type in ('text', 'character varying') then
			seed_user_id_expr := quote_literal('seed');
		elsif user_id_type in ('integer', 'bigint', 'smallint') then
			seed_user_id_expr := '0';
		else
			raise notice 'public.subscriptions.user_id is NOT NULL with unsupported type %, seeding may fail', user_id_type;
			seed_user_id_expr := 'gen_random_uuid()';
		end if;
	end if;

	-- Seed helper (runs 3 times)
	for plan_code_value, plan_name_value in
		select * from (values ('starter','Starter'), ('pro','Pro Artist'), ('elite','Elite Artist')) v(plan_code, plan_name)
	loop
		if plan_code_value = 'starter' then
			plan_price_value := 0;
			plan_duration_days_value := 30;
			plan_features_expr :=
				'jsonb_build_object('
				|| quote_literal('tier') || ',' || quote_literal('starter') || ','
				|| quote_literal('commission_pct') || ',0,'
				|| quote_literal('upload_limits') || ',jsonb_build_object(' || quote_literal('songs') || ',3,' || quote_literal('videos') || ',2),' 
				|| quote_literal('audio_quality') || ',' || quote_literal('standard') || ','
				|| quote_literal('profile') || ',jsonb_build_object(' || quote_literal('public_profile') || ',true),' 
				|| quote_literal('analytics') || ',jsonb_build_object(' || quote_literal('total_plays') || ',true,' || quote_literal('total_likes') || ',true,' || quote_literal('followers') || ',true,' || quote_literal('coins_earned') || ',true),' 
				|| quote_literal('live') || ',jsonb_build_object(' || quote_literal('can_join_battles') || ',true,' || quote_literal('can_host_live') || ',false,' || quote_literal('can_schedule_live') || ',false,' || quote_literal('can_monetize_live') || ',false),' 
				|| quote_literal('ai_music') || ',jsonb_build_object(' || quote_literal('demo_songs_per_month') || ',1,' || quote_literal('max_minutes') || ',1,' || quote_literal('watermarked') || ',true,' || quote_literal('monetizable') || ',false),' 
				|| quote_literal('withdrawal') || ',jsonb_build_object(' || quote_literal('speed') || ',' || quote_literal('standard') || ')' 
				|| ')';
		elsif plan_code_value = 'pro' then
			plan_price_value := 0;
			plan_duration_days_value := 30;
			plan_features_expr :=
				'jsonb_build_object('
				|| quote_literal('tier') || ',' || quote_literal('pro') || ','
				|| quote_literal('billing') || ',jsonb_build_object(' || quote_literal('monthly') || ',true,' || quote_literal('yearly_discounted') || ',true),' 
				|| quote_literal('commission_pct') || ',0,'
				|| quote_literal('upload_limits') || ',jsonb_build_object(' || quote_literal('songs') || ',' || quote_literal('unlimited') || ',' || quote_literal('videos') || ',' || quote_literal('unlimited') || '),' 
				|| quote_literal('audio_quality') || ',' || quote_literal('high') || ','
				|| quote_literal('search_priority') || ',' || quote_literal('priority') || ','
				|| quote_literal('analytics') || ',jsonb_build_object(' || quote_literal('daily_plays') || ',true,' || quote_literal('audience_location') || ',true,' || quote_literal('revenue_tracking') || ',true,' || quote_literal('engagement_rate') || ',true,' || quote_literal('live_performance_stats') || ',true),' 
				|| quote_literal('live') || ',jsonb_build_object(' || quote_literal('can_join_battles') || ',true,' || quote_literal('can_host_live') || ',true,' || quote_literal('can_schedule_live') || ',true,' || quote_literal('can_monetize_live') || ',true,' || quote_literal('provider') || ',' || quote_literal('agora') || '),' 
				|| quote_literal('ai_music') || ',jsonb_build_object(' || quote_literal('songs_per_month') || ',30,' || quote_literal('max_minutes') || ',3,' || quote_literal('custom_lyrics') || ',true,' || quote_literal('genre_mood_selection') || ',true,' || quote_literal('full_quality_export') || ',true,' || quote_literal('monetizable') || ',true),' 
				|| quote_literal('withdrawal') || ',jsonb_build_object(' || quote_literal('speed') || ',' || quote_literal('fast') || ')' 
				|| ')';
		else
			plan_price_value := 0;
			plan_duration_days_value := 30;
			plan_features_expr :=
				'jsonb_build_object('
				|| quote_literal('tier') || ',' || quote_literal('elite') || ','
				|| quote_literal('billing') || ',jsonb_build_object(' || quote_literal('monthly') || ',true,' || quote_literal('yearly_discounted') || ',true),' 
				|| quote_literal('commission_pct') || ',0,'
				|| quote_literal('upload_limits') || ',jsonb_build_object(' || quote_literal('songs') || ',' || quote_literal('unlimited') || ',' || quote_literal('videos') || ',' || quote_literal('unlimited') || '),' 
				|| quote_literal('audio_quality') || ',' || quote_literal('high') || ','
				|| quote_literal('search_priority') || ',' || quote_literal('top') || ','
				|| quote_literal('visibility') || ',jsonb_build_object(' || quote_literal('homepage_banner') || ',true,' || quote_literal('elite_badge') || ',true,' || quote_literal('push_promotions') || ',true,' || quote_literal('top_africa_placement') || ',true),' 
				|| quote_literal('analytics') || ',jsonb_build_object(' || quote_literal('advanced_plus') || ',true),' 
				|| quote_literal('live') || ',jsonb_build_object(' || quote_literal('can_join_battles') || ',true,' || quote_literal('can_host_live') || ',true,' || quote_literal('can_schedule_live') || ',true,' || quote_literal('can_monetize_live') || ',true,' || quote_literal('provider') || ',' || quote_literal('agora') || '),' 
				|| quote_literal('ai_music') || ',jsonb_build_object(' || quote_literal('songs_per_month') || ',' || quote_literal('unlimited') || ',' || quote_literal('max_minutes') || ',5,' || quote_literal('priority_generation') || ',true,' || quote_literal('advanced_customization') || ',true,' || quote_literal('commercial_license') || ',true),' 
				|| quote_literal('withdrawal') || ',jsonb_build_object(' || quote_literal('speed') || ',' || quote_literal('instant_if_balance_ready') || '),' 
				|| quote_literal('support') || ',jsonb_build_object(' || quote_literal('priority') || ',true,' || quote_literal('early_access') || ',true)' 
				|| ')';
		end if;

		-- Build WHERE NOT EXISTS predicate based on available columns.
		if has_plan_code then
			where_pred := format('plan_code = %L', plan_code_value);
		elsif has_name then
			if plan_code_value = 'starter' then
				where_pred := 'lower(trim(name)) in (''starter'',''free'')';
			elsif plan_code_value = 'pro' then
				where_pred := 'lower(trim(name)) in (''pro artist'',''pro'',''premium'')';
			else
				where_pred := 'lower(trim(name)) in (''elite artist'',''elite'',''platinum'')';
			end if;
		else
			raise notice 'public.subscriptions has neither plan_code nor name; cannot seed canonical rows safely.';
			return;
		end if;

		insert_cols := '';
		insert_vals := '';
		missing_required_cols := array[]::text[];

		for col in (
			select
				column_name,
				data_type,
				udt_name,
				is_nullable,
				column_default,
				is_identity
			from information_schema.columns
			where table_schema = 'public'
				and table_name = 'subscriptions'
			order by ordinal_position
		) loop
			-- Skip identity/defaulted columns.
			if coalesce(col.is_identity, 'NO') = 'YES' then
				continue;
			end if;
			if col.column_default is not null then
				continue;
			end if;

			-- Only explicitly set columns we know how to seed, plus any required-without-default columns.
			-- Always attempt to set name/plan_code/plan_name if they exist.
			if col.column_name in ('name', 'plan_code', 'plan_name') then
				null; -- allow below
			elsif col.is_nullable <> 'NO' then
				-- Optional columns: skip unless we have a good mapping.
				expr := null;
				-- Compute a best-effort seed expression for this column.
				if col.column_name = 'user_id' then
					expr := seed_user_id_expr;
				elsif col.column_name in ('role', 'audience') then
					expr := quote_literal('consumer');
				elsif col.column_name in ('plan', 'plan_id', 'plan_code') then
					expr := quote_literal(plan_code_value);
				elsif col.column_name in ('name', 'plan_name') then
					expr := quote_literal(plan_name_value);
				elsif col.column_name in ('status') then
					expr := quote_literal('active');
				elsif col.column_name in ('created_at', 'updated_at') then
					expr := 'now()';
				elsif col.column_name in ('price', 'price_mwk', 'amount') then
					expr := plan_price_value::text;
				elsif col.column_name in ('duration_days', 'duration', 'days') then
					expr := plan_duration_days_value::text;
				elsif col.column_name in ('currency') then
					expr := quote_literal('MWK');
				elsif col.column_name in ('features', 'perks', 'meta') then
					if col.udt_name = 'jsonb' then
						expr := plan_features_expr;
					elsif col.udt_name = 'json' then
						expr := '(' || plan_features_expr || ')::json';
					else
						expr := plan_features_expr;
					end if;
				end if;

				if expr is null then
					continue;
				end if;
			end if;

			-- For required columns without default, we must provide a value.
			if col.is_nullable = 'NO' then
				expr := null;
				if col.column_name = 'user_id' then
					expr := seed_user_id_expr;
				elsif col.column_name in ('role', 'audience') then
					expr := quote_literal('consumer');
				elsif col.column_name in ('plan', 'plan_id', 'plan_code') then
					expr := quote_literal(plan_code_value);
				elsif col.column_name in ('name', 'plan_name') then
					expr := quote_literal(plan_name_value);
				elsif col.column_name in ('status') then
					expr := quote_literal('active');
				elsif col.column_name in ('created_at', 'updated_at') then
					expr := 'now()';
				elsif col.column_name in ('price', 'price_mwk', 'amount') then
					expr := plan_price_value::text;
				elsif col.column_name in ('duration_days', 'duration', 'days') then
					expr := plan_duration_days_value::text;
				elsif col.column_name in ('currency') then
					expr := quote_literal('MWK');
				elsif col.column_name in ('features', 'perks', 'meta') then
					if col.udt_name = 'jsonb' then
						expr := plan_features_expr;
					elsif col.udt_name = 'json' then
						expr := '(' || plan_features_expr || ')::json';
					else
						expr := plan_features_expr;
					end if;
				end if;

				if expr is null then
					missing_required_cols := array_append(missing_required_cols, col.column_name);
					continue;
				end if;
			end if;

			-- Add this column/value.
			insert_cols := insert_cols || case when insert_cols = '' then '' else ',' end || format('%I', col.column_name);
			-- expr might not be set for nullable columns, so compute again for safety.
			expr := null;
			if col.column_name = 'user_id' then
				expr := seed_user_id_expr;
			elsif col.column_name in ('role', 'audience') then
				expr := quote_literal('consumer');
			elsif col.column_name in ('plan', 'plan_id', 'plan_code') then
				expr := quote_literal(plan_code_value);
			elsif col.column_name in ('name', 'plan_name') then
				expr := quote_literal(plan_name_value);
			elsif col.column_name in ('status') then
				expr := quote_literal('active');
			elsif col.column_name in ('created_at', 'updated_at') then
				expr := 'now()';
			elsif col.column_name in ('price', 'price_mwk', 'amount') then
				expr := plan_price_value::text;
			elsif col.column_name in ('duration_days', 'duration', 'days') then
				expr := plan_duration_days_value::text;
			elsif col.column_name in ('currency') then
				expr := quote_literal('MWK');
			elsif col.column_name in ('features', 'perks', 'meta') then
				if col.udt_name = 'jsonb' then
					expr := plan_features_expr;
				elsif col.udt_name = 'json' then
					expr := '(' || plan_features_expr || ')::json';
				else
					expr := plan_features_expr;
				end if;
			end if;
			insert_vals := insert_vals || case when insert_vals = '' then '' else ',' end || coalesce(expr, 'null');
		end loop;

		if array_length(missing_required_cols, 1) is not null then
			raise notice 'Skipping subscriptions seed for % due to required columns without defaults that cannot be auto-filled: %', plan_code_value, array_to_string(missing_required_cols, ',');
			continue;
		end if;

		execute format(
			'insert into public.subscriptions (%s) select %s where not exists (select 1 from public.subscriptions where %s)',
			insert_cols,
			insert_vals,
			where_pred
		);
	end loop;

	-- Backfill for any pre-existing rows (best-effort).
	update public.subscriptions
	set plan_name = case
		when lower(trim(coalesce(plan_code, ''))) = 'starter' then 'Starter'
		when lower(trim(coalesce(plan_code, ''))) = 'pro' then 'Pro Artist'
		when lower(trim(coalesce(plan_code, ''))) = 'elite' then 'Elite Artist'
		else coalesce(plan_name, name)
	end
	where plan_name is null;

	update public.subscriptions
	set plan_code = case
		when lower(trim(name)) in ('starter', 'free') then 'starter'
		when lower(trim(name)) in ('pro artist', 'pro', 'premium') then 'pro'
		when lower(trim(name)) in ('elite artist', 'elite', 'platinum') then 'elite'
		else plan_code
	end
	where plan_code is null;

	update public.subscriptions
	set plan_name = case
		when lower(trim(coalesce(plan_code, ''))) = 'starter' then 'Starter'
		when lower(trim(coalesce(plan_code, ''))) = 'pro' then 'Pro Artist'
		when lower(trim(coalesce(plan_code, ''))) = 'elite' then 'Elite Artist'
		else plan_name
	end
	where lower(trim(coalesce(plan_code, ''))) in ('starter', 'pro', 'elite');
end $$;

-- Hint PostgREST to refresh schema cache.
notify pgrst, 'reload schema';
