-- Rename existing JSON rules table away from `subscription_content_access` and
-- recreate `subscription_content_access` as the per-content mapping table (requested schema).
--
-- Existing (admin rules UI): public.subscription_content_access(plan_id, rules, ...)
-- Requested (per-item): public.subscription_content_access(id, subscription_id, content_id, access_level)

create extension if not exists pgcrypto;

-- 0) Ensure updated_at trigger helper exists.
create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

-- 1) Rename the existing JSON rules table (if present).
-- This preserves data for the admin UI, but frees the name for the requested schema.
do $$
begin
	if exists (
		select 1
		from information_schema.tables
		where table_schema = 'public'
			and table_name = 'subscription_content_access'
	)
	and not exists (
		select 1
		from information_schema.tables
		where table_schema = 'public'
			and table_name = 'subscription_plan_content_rules'
	) then
		alter table public.subscription_content_access
			rename to subscription_plan_content_rules;
	end if;
end $$;

create unique index if not exists subscription_plan_content_rules_plan_id_unique
	on public.subscription_plan_content_rules (plan_id);

-- 2) Create the requested per-content mapping table.
do $$
declare
	subs_type text;
begin
	select data_type into subs_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscriptions'
		and column_name = 'id';

	if subs_type is null then
		subs_type := 'integer';
	end if;

	execute format(
		'create table if not exists public.subscription_content_access (
			id integer generated by default as identity primary key,
			subscription_id %s not null references public.subscriptions (id) on delete cascade,
			content_id uuid not null,
			access_level text not null default ''full'' check (access_level in (''full'',''limited'')),
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)',
		subs_type
	);
end $$;

create unique index if not exists subscription_content_access_subscription_content_unique
	on public.subscription_content_access (subscription_id, content_id);

create index if not exists subscription_content_access_subscription_id_idx
	on public.subscription_content_access (subscription_id);

create index if not exists subscription_content_access_content_id_idx
	on public.subscription_content_access (content_id);

-- Validate content_id exists in songs OR videos.
create or replace function public.tg_validate_subscription_content_access()
returns trigger
language plpgsql
as $$
begin
	if not exists (select 1 from public.songs where id = new.content_id)
		and not exists (select 1 from public.videos where id = new.content_id)
	then
		raise exception 'Invalid content_id %, not found in songs/videos', new.content_id;
	end if;
	return new;
end;
$$;

do $$
begin
	if not exists (select 1 from pg_trigger where tgname = 'subscription_content_access_validate') then
		create trigger subscription_content_access_validate
			before insert or update on public.subscription_content_access
			for each row
			execute function public.tg_validate_subscription_content_access();
	end if;

	if not exists (select 1 from pg_trigger where tgname = 'subscription_content_access_set_updated_at') then
		create trigger subscription_content_access_set_updated_at
			before update on public.subscription_content_access
			for each row
			execute function public.tg_set_updated_at();
	end if;
end $$;

-- 3) RLS: match repo's default deny-all posture (service-role bypass still works).
alter table public.subscription_content_access enable row level security;

do $$
begin
	if not exists (
		select 1
		from pg_policies
		where schemaname = 'public'
			and tablename = 'subscription_content_access'
			and policyname = 'deny_all_subscription_content_access'
	) then
		create policy deny_all_subscription_content_access
			on public.subscription_content_access
			for all
			using (false)
			with check (false);
	end if;
end $$;