-- Align schema with requested admin subscription tables without breaking existing dashboard tables.
--
-- Requested spec:
-- - subscriptions (id int, name, price, duration_days, features, status, timestamps)
-- - user_subscriptions (id int, user_id uuid, subscription_id int, start_date/end_date, status, payment_id, timestamps)
-- - subscription_content_access (optional per-content map)
--
-- This repo already contains:
-- - subscription_plans (canonical plan catalog, keyed by plan_id text)
-- - user_subscriptions (keyed by id bigserial, references subscription_plans.plan_id)
-- - subscription_content_access (JSON rules per plan_id)
--
-- To avoid breaking existing code, this migration:
-- 1) Creates public.subscriptions as an ID-based catalog.
-- 2) Adds subscription_id/start_date/end_date/payment_id to existing public.user_subscriptions.
-- 3) Links subscription_plans <-> subscriptions via subscription_plans.subscription_id.
-- 4) Adds an optional per-content mapping table with a non-conflicting name.

create extension if not exists pgcrypto;
-- 0) updated_at trigger helper (used across multiple tables)
create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;
-- 1) A) subscriptions table (new)
create table if not exists public.subscriptions (
	id integer generated by default as identity primary key,
	name text not null unique,
	price integer not null default 0 check (price >= 0),
	duration_days integer not null default 30 check (duration_days > 0),
	features jsonb not null default '{}'::jsonb,
	status text not null default 'active' check (status in ('active','inactive')),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);
-- If the table already exists from an older schema, ensure the columns this repo expects exist.
-- NOTE: We intentionally avoid adding NOT NULL constraints here to prevent breaking legacy data.
alter table public.subscriptions
	add column if not exists name text,
	add column if not exists price integer,
	add column if not exists duration_days integer,
	add column if not exists features jsonb,
	add column if not exists status text,
	add column if not exists created_at timestamptz,
	add column if not exists updated_at timestamptz;
-- Ensure the ON CONFLICT(name) seed works even if the legacy table didn't have a unique constraint.
create unique index if not exists subscriptions_name_unique on public.subscriptions (name);
create index if not exists subscriptions_status_idx on public.subscriptions (status);
alter table public.subscriptions enable row level security;
do $$
begin
	if not exists (
		select 1
		from pg_policies
		where schemaname = 'public'
			and tablename = 'subscriptions'
			and policyname = 'deny_all_subscriptions'
	) then
		create policy deny_all_subscriptions
			on public.subscriptions
			for all
			using (false)
			with check (false);
	end if;
end $$;
-- Seed catalog (idempotent), unless a legacy NOT NULL user_id exists.
do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'subscriptions'
			and column_name = 'user_id'
			and is_nullable = 'NO'
	) then
		raise notice 'Skipping subscriptions seed due to legacy NOT NULL user_id column';
	else
		insert into public.subscriptions (name, price, duration_days, features, status)
		values
			('Free', 0, 30, '{}'::jsonb, 'active'),
			('Premium', 0, 30, '{}'::jsonb, 'active'),
			('Platinum', 0, 30, '{}'::jsonb, 'active')
		on conflict (name) do update set
			status = excluded.status,
			duration_days = excluded.duration_days,
			updated_at = now();
	end if;
end
$$;
do $$
begin
	if not exists (
		select 1 from pg_trigger
		where tgname = 'subscriptions_set_updated_at'
	) then
		create trigger subscriptions_set_updated_at
		before update on public.subscriptions
		for each row
		execute function public.tg_set_updated_at();
	end if;
end $$;
-- 2) Link existing subscription_plans to subscriptions
alter table public.subscription_plans
	add column if not exists subscription_id integer;
do $$
declare
	plans_type text;
	subs_type text;
begin
	select data_type into plans_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscription_plans'
		and column_name = 'subscription_id';

	select data_type into subs_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscriptions'
		and column_name = 'id';

	-- Add FK only when not present and types match
	if plans_type is not null and subs_type is not null and plans_type = subs_type then
		if not exists (
			select 1
			from information_schema.table_constraints tc
			where tc.table_schema = 'public'
				and tc.table_name = 'subscription_plans'
				and tc.constraint_type = 'FOREIGN KEY'
				and tc.constraint_name = 'subscription_plans_subscription_id_fkey'
		) then
			alter table public.subscription_plans
				add constraint subscription_plans_subscription_id_fkey
				foreign key (subscription_id)
				references public.subscriptions (id)
				on delete set null;
		end if;
	else
		raise notice 'Skipping subscription_plans.subscription_id FK due to incompatible types: % vs %', plans_type, subs_type;
	end if;
end $$;
create index if not exists subscription_plans_subscription_id_idx
	on public.subscription_plans (subscription_id);
-- Backfill subscription_plans.subscription_id by matching plan_id <-> subscriptions.name
do $$
declare
	plans_type text;
	subs_type text;
begin
	select data_type into plans_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscription_plans'
		and column_name = 'subscription_id';

	select data_type into subs_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscriptions'
		and column_name = 'id';

	if plans_type is not null and subs_type is not null and plans_type = subs_type then
		update public.subscription_plans sp
		set subscription_id = s.id
		from public.subscriptions s
		where sp.subscription_id is null
			and lower(sp.plan_id) = lower(s.name);
	else
		raise notice 'Skipping subscription_plans.subscription_id backfill due to incompatible types: % vs %', plans_type, subs_type;
	end if;
end $$;
-- Keep subscriptions.features/price in sync with subscription_plans when possible
update public.subscriptions s
set
	price = sp.price_mwk,
	features = coalesce(sp.features, '{}'::jsonb),
	updated_at = now()
from public.subscription_plans sp
where lower(sp.plan_id) = lower(s.name);
-- Also sync active/inactive state when available.
update public.subscriptions s
set
	status = case when sp.is_active then 'active' else 'inactive' end,
	updated_at = now()
from public.subscription_plans sp
where lower(sp.plan_id) = lower(s.name)
	and sp.is_active is not null;
do $$
begin
	if not exists (
		select 1 from pg_trigger
		where tgname = 'subscription_plans_set_updated_at'
	) then
		create trigger subscription_plans_set_updated_at
		before update on public.subscription_plans
		for each row
		execute function public.tg_set_updated_at();
	end if;
end $$;
-- 3) B) Extend existing user_subscriptions table to support requested columns
-- Add missing columns with requested names.
alter table public.user_subscriptions
	add column if not exists subscription_id integer,
	add column if not exists start_date timestamptz,
	add column if not exists end_date timestamptz,
	add column if not exists payment_id text;
-- Ensure status accepts the requested spelling (cancelled) while preserving existing values.
alter table public.user_subscriptions
	drop constraint if exists user_subscriptions_status_check;
alter table public.user_subscriptions
	add constraint user_subscriptions_status_check
	check (status in ('active','canceled','cancelled','expired','replaced'));
-- If user_id is stored as text but contains UUIDs, safely convert to uuid and reference auth.users.
do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'user_subscriptions'
			and column_name = 'user_id'
			and data_type in ('text','character varying')
	) then
		-- Only convert when we have existing rows and ALL user_id values match UUID format.
		-- This avoids breaking Firebase-based setups where user_id is a Firebase uid.
		if exists (select 1 from public.user_subscriptions limit 1)
			and not exists (
				select 1
				from public.user_subscriptions
				where user_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
			) then
			alter table public.user_subscriptions
				alter column user_id type uuid using user_id::uuid;
		end if;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'user_subscriptions'
			and column_name = 'user_id'
			and data_type = 'uuid'
	) then
		if not exists (
			select 1
			from information_schema.table_constraints tc
			where tc.table_schema = 'public'
				and tc.table_name = 'user_subscriptions'
				and tc.constraint_type = 'FOREIGN KEY'
				and tc.constraint_name = 'user_subscriptions_user_id_fkey'
		) then
			alter table public.user_subscriptions
				add constraint user_subscriptions_user_id_fkey
				foreign key (user_id)
				references auth.users (id)
				on delete cascade;
		end if;
	end if;
end $$;
-- Add FK to subscriptions (id-based) but keep plan_id for existing code.
do $$
declare
	us_type text;
	subs_type text;
begin
	select data_type into us_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'user_subscriptions'
		and column_name = 'subscription_id';

	select data_type into subs_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscriptions'
		and column_name = 'id';

	if us_type is not null and subs_type is not null and us_type = subs_type then
		if not exists (
			select 1
			from information_schema.table_constraints tc
			where tc.table_schema = 'public'
				and tc.table_name = 'user_subscriptions'
				and tc.constraint_type = 'FOREIGN KEY'
				and tc.constraint_name = 'user_subscriptions_subscription_id_fkey'
		) then
			alter table public.user_subscriptions
				add constraint user_subscriptions_subscription_id_fkey
				foreign key (subscription_id)
				references public.subscriptions (id)
				on delete set null;
		end if;
	else
		raise notice 'Skipping user_subscriptions.subscription_id FK due to incompatible types: % vs %', us_type, subs_type;
	end if;
end $$;
create index if not exists user_subscriptions_subscription_id_idx
	on public.user_subscriptions (subscription_id);
create index if not exists user_subscriptions_payment_id_idx
	on public.user_subscriptions (payment_id);
-- Backfill: subscription_id/start_date/end_date from existing columns
do $$
declare
	us_type text;
	plans_type text;
begin
	select data_type into us_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'user_subscriptions'
		and column_name = 'subscription_id';

	select data_type into plans_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscription_plans'
		and column_name = 'subscription_id';

	if us_type is not null and plans_type is not null and us_type = plans_type then
		update public.user_subscriptions us
		set
			start_date = coalesce(us.start_date, us.started_at),
			end_date = coalesce(us.end_date, us.ends_at),
			subscription_id = coalesce(us.subscription_id, sp.subscription_id)
		from public.subscription_plans sp
		where us.plan_id = sp.plan_id;
	else
		raise notice 'Skipping subscription_id backfill due to incompatible types: % vs %', us_type, plans_type;
		update public.user_subscriptions us
		set
			start_date = coalesce(us.start_date, us.started_at),
			end_date = coalesce(us.end_date, us.ends_at)
		where us.started_at is not null or us.ends_at is not null;
	end if;
end $$;
-- Compatibility trigger:
-- - ensures start_date/end_date stay in sync with started_at/ends_at
-- - auto-populates subscription_id based on plan_id when possible
create or replace function public.tg_user_subscriptions_compat()
returns trigger
language plpgsql
as $$
begin
	if new.start_date is null and new.started_at is not null then
		new.start_date = new.started_at;
	end if;

	if new.started_at is null and new.start_date is not null then
		new.started_at = new.start_date;
	end if;

	if new.end_date is null and new.ends_at is not null then
		new.end_date = new.ends_at;
	end if;

	if new.ends_at is null and new.end_date is not null then
		new.ends_at = new.end_date;
	end if;

	if new.subscription_id is null and new.plan_id is not null then
		select sp.subscription_id
			into new.subscription_id
		from public.subscription_plans sp
		where sp.plan_id = new.plan_id
		limit 1;
	end if;

	return new;
end;
$$;
do $$
begin
	if not exists (
		select 1 from pg_trigger
		where tgname = 'user_subscriptions_compat'
	) then
		create trigger user_subscriptions_compat
		before insert or update on public.user_subscriptions
		for each row
		execute function public.tg_user_subscriptions_compat();
	end if;
end $$;
do $$
begin
	if not exists (
		select 1 from pg_trigger
		where tgname = 'user_subscriptions_set_updated_at'
	) then
		create trigger user_subscriptions_set_updated_at
		before update on public.user_subscriptions
		for each row
		execute function public.tg_set_updated_at();
	end if;
end $$;
-- 4) C) Optional per-content access mapping
-- NOTE: The name `subscription_content_access` is already used for JSON rules per plan.
-- This table provides the requested per-content mapping without colliding.
do $$
declare
	subs_type text;
begin
	select data_type into subs_type
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'subscriptions'
		and column_name = 'id';

	if subs_type is null then
		subs_type := 'integer';
	end if;

	execute format(
		'create table if not exists public.subscription_content_access_items (
			id integer generated by default as identity primary key,
			subscription_id %s not null references public.subscriptions (id) on delete cascade,
			content_type text not null check (content_type in (''songs'',''videos'')),
			content_id uuid not null,
			access_level text not null default ''full'' check (access_level in (''full'',''limited'')),
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)',
		subs_type
	);
end $$;
alter table public.subscription_content_access_items enable row level security;
do $$
begin
	if not exists (
		select 1
		from pg_policies
		where schemaname = 'public'
			and tablename = 'subscription_content_access_items'
			and policyname = 'deny_all_subscription_content_access_items'
	) then
		create policy deny_all_subscription_content_access_items
			on public.subscription_content_access_items
			for all
			using (false)
			with check (false);
	end if;
end $$;
create index if not exists subscription_content_access_items_subscription_idx
	on public.subscription_content_access_items (subscription_id);
create index if not exists subscription_content_access_items_content_idx
	on public.subscription_content_access_items (content_type, content_id);
-- Enforce content existence based on content_type (trigger-based integrity)
create or replace function public.tg_validate_subscription_content_access_item()
returns trigger
language plpgsql
as $$
begin
	if new.content_type = 'songs' then
		if not exists (select 1 from public.songs where id = new.content_id) then
			raise exception 'Invalid content_id %, no row in public.songs', new.content_id;
		end if;
	elsif new.content_type = 'videos' then
		if not exists (select 1 from public.videos where id = new.content_id) then
			raise exception 'Invalid content_id %, no row in public.videos', new.content_id;
		end if;
	else
		raise exception 'Invalid content_type %', new.content_type;
	end if;
	return new;
end;
$$;
do $$
begin
	if not exists (
		select 1
		from pg_trigger
		where tgname = 'subscription_content_access_items_validate'
	) then
		create trigger subscription_content_access_items_validate
		before insert or update on public.subscription_content_access_items
		for each row
		execute function public.tg_validate_subscription_content_access_item();
	end if;

	if not exists (
		select 1 from pg_trigger
		where tgname = 'subscription_content_access_items_set_updated_at'
	) then
		create trigger subscription_content_access_items_set_updated_at
		before update on public.subscription_content_access_items
		for each row
		execute function public.tg_set_updated_at();
	end if;
end $$;
