-- Risk flags & suggestions (server-only reads/writes via service role)

create table if not exists public.risk_flags (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  status text not null default 'open' check (status in ('open','dismissed','resolved')),
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),

  kind text not null,
  entity_type text not null check (entity_type in ('artist','dj','stream','withdrawal')),
  entity_id text not null,

  country_code text null,

  title text not null,
  description text not null,
  evidence jsonb not null default '{}'::jsonb,
  suggested_actions jsonb not null default '[]'::jsonb,

  fingerprint text not null unique,

  resolved_at timestamptz,
  resolved_by_email text,
  resolution_note text
);
create index if not exists risk_flags_created_at_idx on public.risk_flags (created_at desc);
create index if not exists risk_flags_status_idx on public.risk_flags (status);
create index if not exists risk_flags_severity_idx on public.risk_flags (severity);
create index if not exists risk_flags_entity_idx on public.risk_flags (entity_type, entity_id);
create index if not exists risk_flags_kind_idx on public.risk_flags (kind);
create index if not exists risk_flags_country_idx on public.risk_flags (country_code);
alter table public.risk_flags enable row level security;
-- deny-all by default (service role bypasses RLS)
create policy "deny all" on public.risk_flags for all using (false) with check (false);
