-- STEP 10 — Learning DJ AI (Machine Learning v1)
--
-- Stores DJ AI decisions + battle context so we can train models from WeAfrica data.
-- Also includes a small "policy" table that can be populated by offline training
-- and queried by the Edge Function for hybrid (ML + rules) decisions.

create table if not exists public.dj_ai_events (
	id bigint generated by default as identity primary key,
	created_at timestamptz not null default now(),

	battle_id text,
	battle_type text,
	user_id text,

	style text,

	current_song_id text,
	current_song_bpm int not null,
	current_song_energy double precision,
	current_song_genre text,

	likes_per_min int not null,
	coins_per_min int not null,
	viewers_change int not null default 0,
	battle_time_remaining int,

	pressure_score double precision,
	pressure_state text,

	rule_decision text,
	ml_decision text,
	decision text not null,
	next_song_id text not null,

	reasons jsonb,
	outcome text,
	extra jsonb
);
create index if not exists idx_dj_ai_events_created_at on public.dj_ai_events(created_at desc);
create index if not exists idx_dj_ai_events_battle_id on public.dj_ai_events(battle_id);
create index if not exists idx_dj_ai_events_style on public.dj_ai_events(style);
create index if not exists idx_dj_ai_events_decision on public.dj_ai_events(decision);
-- Learned policy lookup table (populated by offline training).
create table if not exists public.dj_ai_policy (
	style text not null,
	pressure_state text not null,
	bpm_bin int not null,
	likes_bin int not null,
	coins_bin int not null,
	viewers_bin int not null,
	decision text not null,
	confidence double precision not null default 0,
	updated_at timestamptz not null default now(),
	primary key (style, pressure_state, bpm_bin, likes_bin, coins_bin, viewers_bin)
);
create index if not exists idx_dj_ai_policy_updated_at on public.dj_ai_policy(updated_at desc);
-- Security: keep raw ML training data private by default.
-- Edge Function uses service_role for inserts/selects.
alter table public.dj_ai_events enable row level security;
alter table public.dj_ai_policy enable row level security;
revoke all on table public.dj_ai_events from anon, authenticated;
revoke all on table public.dj_ai_policy from anon, authenticated;
-- service_role bypasses RLS, but keep explicit grants tidy.
grant all on table public.dj_ai_events to service_role;
grant all on table public.dj_ai_policy to service_role;
