-- Analytics events telemetry (server-only reads/writes via service role)

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  event_name text not null,
  user_id text null,
  actor_type text null,
  actor_id text null,
  session_id text null,

  country_code text null,
  stream_id text null,

  platform text null,
  app_version text null,
  source text null,

  properties jsonb null
);
create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_name_idx on public.analytics_events (event_name);
create index if not exists analytics_events_user_id_idx on public.analytics_events (user_id);
create index if not exists analytics_events_event_created_idx on public.analytics_events (event_name, created_at desc);
create index if not exists analytics_events_stream_id_idx on public.analytics_events (stream_id);
alter table public.analytics_events enable row level security;
-- deny-all by default (service role bypasses RLS)
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'deny all'
  ) then
    execute 'create policy "deny all" on public.analytics_events for all using (false) with check (false)';
  end if;
end
$$;
-- Distinct user counts (DAU/MAU, etc)
create or replace function public.analytics_distinct_users(
  p_since timestamptz,
  p_event_name text,
  p_country_code text default null
) returns bigint
language sql
stable
as $$
  select count(distinct user_id)::bigint
  from public.analytics_events
  where created_at >= p_since
    and event_name = p_event_name
    and user_id is not null
    and (p_country_code is null or country_code = p_country_code);
$$;
-- Daily distinct users series (e.g. DAU trend)
create or replace function public.analytics_daily_distinct_users(
  p_days int,
  p_event_name text,
  p_country_code text default null
) returns table(day date, value bigint)
language sql
stable
as $$
  with filtered as (
    select created_at::date as day, user_id
    from public.analytics_events
    where created_at >= (now() - (greatest(1, least(365, p_days)) || ' days')::interval)
      and event_name = p_event_name
      and user_id is not null
      and (p_country_code is null or country_code = p_country_code)
  )
  select day, count(distinct user_id)::bigint as value
  from filtered
  group by day
  order by day;
$$;
-- Daily total event counts series
create or replace function public.analytics_daily_event_count(
  p_days int,
  p_event_name text,
  p_country_code text default null
) returns table(day date, value bigint)
language sql
stable
as $$
  select created_at::date as day, count(*)::bigint as value
  from public.analytics_events
  where created_at >= (now() - (greatest(1, least(365, p_days)) || ' days')::interval)
    and event_name = p_event_name
    and (p_country_code is null or country_code = p_country_code)
  group by day
  order by day;
$$;
-- Streaming join success rate from telemetry
-- Convention: event_name = 'stream_join', properties.ok = true/false
create or replace function public.analytics_stream_join_success_rate(
  p_days int,
  p_country_code text default null
) returns table(attempts bigint, successes bigint, success_rate double precision)
language sql
stable
as $$
  with filtered as (
    select (properties->>'ok')::boolean as ok
    from public.analytics_events
    where created_at >= (now() - (greatest(1, least(365, p_days)) || ' days')::interval)
      and event_name = 'stream_join'
      and (p_country_code is null or country_code = p_country_code)
  )
  select
    count(*)::bigint as attempts,
    count(*) filter (where ok is true)::bigint as successes,
    case when count(*) = 0 then null else (count(*) filter (where ok is true))::double precision / count(*)::double precision end as success_rate
  from filtered;
$$;
