export enum DomainEvent {
  STREAM_CREATED = 'STREAM_CREATED',
  STREAM_STARTED = 'STREAM_STARTED',
  STREAM_ENDED = 'STREAM_ENDED',
  BATTLE_INVITE_SENT = 'BATTLE_INVITE_SENT',
  BATTLE_ACCEPTED = 'BATTLE_ACCEPTED',
  BATTLE_ENDED = 'BATTLE_ENDED',
  GIFT_SENT = 'GIFT_SENT',
  VOTE_CAST = 'VOTE_CAST',
  VIEWER_COUNT_UPDATED = 'VIEWER_COUNT_UPDATED',
}
